### ISSUE TITLE
Etcd Minimum Set Of Config

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#14]
We should determine the minimum relevant set of configuration for etcd that is needed to 1. bootstrap the cluster, and 2. add a new node to the cluster. The union of the two should be the complete set of config that we need our early-stage library.

**Comment by JackyChiu** [comment]
Pretty sure this is it: (advertise configs might be able to be removed)
```yaml
# Human-readable name for this member.
name: node1

# Path to the data directory.
data-dir: tmp1

# List of comma separated URLs to listen on for peer traffic.
listen-peer-urls: http://127.0.0.1:12380

# List of comma separated URLs to listen on for client traffic.
listen-client-urls: http://127.0.0.1:12379

# List of this member's peer URLs to advertise to the rest of the cluster.
# The URLs needed to be a comma-separated list.
initial-advertise-peer-urls: http://127.0.0.1:12380

# List of this member's client URLs to advertise to the public.
# The URLs needed to be a comma-separated list.
advertise-client-urls: http://127.0.0.1:12379

# Initial cluster configuration for bootstrapping.
initial-cluster: node1=http://127.0.0.1:12380

# Initial cluster token for the etcd cluster during bootstrap.
initial-cluster-token: 'etcd-cluster'

# Initial cluster state ('new' or 'existing').
initial-cluster-state: 'new'

```
